### PR TITLE
set `query_new_status` to progress if job status is progress

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Review by dsavchenko — APPROVED** [review]

**Comment by burnout87** [comment]
Can you merge yet @dsavchenko  ?

**Review by volodymyrss — APPROVED** [review]

**Comment by volodymyrss** [comment]
> Can you merge yet @dsavchenko ?

@dsavchenko has the same rights as you @burnout87 . I suppose @dsavchenko was waiting (correctly) for the review which was incomplete.

**Comment by burnout87** [comment]
> > Can you merge yet @dsavchenko ?
> 
> @dsavchenko has the same rights as you @burnout87 . I suppose @dsavchenko was waiting (correctly) for the review which was incomplete.

I remember in the past he could not since he was not granted permissions,

**Comment by dsavchenko** [comment]
Yes, now I have a permission to merge

**Comment by volodymyrss** [comment]
> Yes, now I have a permission to merge

It's all approved, you can merge if you want. Or if you want to make more changes - make them, re-request review.

**Pull request merged**
