### PR TITLE
sentry message invalid usage run_analysis

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Review by volodymyrss — CHANGES_REQUESTED** [review]
Thanks! 
Since we are onto it, could we simply change the status code to 500? 410 means something quite different.
We can then adapt the latest changes in `oda_api` too.

And also rename  `InvalidUsage` to something like `UnknownDispatcherException`.

**Comment by burnout87** [comment]
>
>  We can then adapt the latest changes in oda_api too.

Is it actually used within the `oda_api`? I did a quick search and didn't find any use

**Comment by volodymyrss** [comment]
> > We can then adapt the latest changes in oda_api too.
> 
> Is it actually used within the `oda_api`? I did a quick search and didn't find any use

We just merged it!

https://github.com/oda-hub/oda_api/blob/master/oda_api/api.py#L416

**Comment by burnout87** [comment]
> > > We can then adapt the latest changes in oda_api too.
> > 
> > 
> > Is it actually used within the `oda_api`? I did a quick search and didn't find any use
> 
> We just merged it! _edit: i.e. you just reviewed it :)_
> 
> https://github.com/oda-hub/oda_api/blob/master/oda_api/api.py#L416

I was specifically talking about the ` InvalidUsage` exception

**Comment by volodymyrss** [comment]
> > > > We can then adapt the latest changes in oda_api too.
> > > 
> > > 
> > > Is it actually used within the `oda_api`? I did a quick search and didn't find any use
> > 
> > 
> > We just merged it! _edit: i.e. you just reviewed it :)_
> > https://github.com/oda-hub/oda_api/blob/master/oda_api/api.py#L416
> 
> I was specifically talking about the ` c` exception
> 
> edit: we intercept the 410 code, not the specific exception, reason why was asking

I am not sure what you mean at all by intercepting dispatcher exception in oda_api. 
The only way oda_api communicates with the dispatcher is through HTTP requests, with status codes and messages.
So InvalidUsage is only generated (and can be caught directly) on the server, and transported to oda_api in response with 410 status.
And oda_api effectively intercepts InvalidUsage by treating 410 code.

**Comment by burnout87** [comment]
> 
> I am not sure what you mean at all by intercepting dispatcher exception in oda_api. The only way oda_api communicates with the dispatcher is through HTTP requests, with status codes and messages. So InvalidUsage is only generated (and can be caught directly) on the server, and transported to oda_api in response with 410 status. And oda_api effectively intercepts InvalidUsage by treating 410 code.

I meant that `oda_api` would intercept directly the `InvalidUsage` exception and I obviously did the wrong assumption so, I got confused with the naming and the rest, once this is merged we'll make also the necessary adaptation in the `oda_api`.

**Review by volodymyrss — APPROVED** [review]

**Pull request merged**
