### PR TITLE
dummy plugin and relative reload test

### PR DESCRIPTION
**Pull request by burnout87**
here an empty plugin with a relative test

surely not the neatest solution, so open to suggestions for improvements

### CODE REVIEW

**Review by volodymyrss — APPROVED** [review]
nice, seems ok for me, but I did not look deep.

**Comment by dsavchenko** [comment]
The functionality and it's mechanics do not really mimic the actual usecase, so it looks for me like unneded modifications. 
Still ok, because I don't currently have another solution (but I will try)

**Comment by burnout87** [comment]
> The functionality and it's mechanics do not really mimic the actual usecase, so it looks for me like unneded modifications. Still ok, because I don't currently have another solution (but I will try)

You're right but it would probably take a lot more time to build an entire `dummy` plugin that would allow us to fully reproduce the same behavior of re-loading of a standard plugin

**Comment by volodymyrss** [comment]
so we do not need this? @burnout87

**Comment by burnout87** [comment]
No, can be closed as #457 provides a more complete approach

**Pull request closed without merging**
