### PR TITLE
missing sentry dsn after url call fails and as arg to a number of calls

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Review by volodymyrss — APPROVED** [review]

**Comment by burnout87** [comment]
Tests of oda_api fail because of `test_instruments`. I could not even run it locally

**Comment by volodymyrss** [comment]
> Tests of oda_api fail because of `test_instruments`. I could not even run it locally

why?

**Comment by burnout87** [comment]
> > Tests of oda_api fail because of `test_instruments`. I could not even run it locally
> 
> why?

There seems to be an issue when running `api/instr-list`. 

`urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='oda-dispatcher', port=8000): Max retries exceeded with url: /instr-list?instrument=mock (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe4198347f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))`

**Comment by volodymyrss** [comment]
> > > Tests of oda_api fail because of `test_instruments`. I could not even run it locally
> > 
> > 
> > why?
> 
> There seems to be an issue when running `api/instr-list`.
> 
> `urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='oda-dispatcher', port=8000): Max retries exceeded with url: /instr-list?instrument=mock (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe4198347f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))`

is this also locally?

should it really be `oda-dispatcher` ? It should be localhost something, from fixture. No?

**Comment by burnout87** [comment]
> 
> is this also locally?
> 
> should it really be `oda-dispatcher` ? It should be localhost something, from fixture. No?

The test `test_instruments` queries the production dispatcher: https://github.com/oda-hub/oda_api/blob/f6b6d2f5b45244022aa684e5175c560a4dc08dc2/tests/test_live.py#L84-L90

**Comment by volodymyrss** [comment]
> > is this also locally?
> > should it really be `oda-dispatcher` ? It should be localhost something, from fixture. No?
> 
> The test `test_instruments` queries the production dispatcher: https://github.com/oda-hub/oda_api/blob/f6b6d2f5b45244022aa684e5175c560a4dc08dc2/tests/test_live.py#L84-L90

so something made a backward-incompatible change. What?

**Comment by burnout87** [comment]
> 
> so something made a backward-incompatible change. What?

When I implemented #504 I changed the behavior of that endpoint introducing a redirection, but all the tests (and also for other PRs) passed.

**Comment by volodymyrss** [comment]
> > so something made a backward-incompatible change. What?
> 
> When I implemented #504 I changed the behavior of that endpoint introducing a redirection, but all the tests (and also for other PRs) passed.

uh, I should have paid more attention in review.

the redirect is incorrect:

```bash
$ curl -v https://www.astro.unige.ch/mmoda/dispatch-data/api/instr-list
http://oda-dispatcher:8000/instr-list
```

the redirect should use public url, or better just relative path. Please add a test  to make sure that the url_for in this case returns either external url (as in the config) or relative path. I will make a hotfix  since it is critical.

**Comment by burnout87** [comment]
> 
> uh, I should have paid more attention in review.
> 
> the redirect is incorrect:
> 
> ```shell
> $ curl -v https://www.astro.unige.ch/mmoda/dispatch-data/api/instr-list
> http://oda-dispatcher:8000/instr-list
> ```
> 
> the redirect should use public url, or better just relative path. Please add a test to make sure that the url_for in this case returns either external url (as in the config) or relative path. I will make a hotfix since it is critical.

Also it was missed as only recently it was pushed in he production

**Comment by volodymyrss** [comment]
> > uh, I should have paid more attention in review.
> > the redirect is incorrect:
> > ```shell
> > $ curl -v https://www.astro.unige.ch/mmoda/dispatch-data/api/instr-list
> > http://oda-dispatcher:8000/instr-list
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the redirect should use public url, or better just relative path. Please add a test to make sure that the url_for in this case returns either external url (as in the config) or relative path. I will make a hotfix since it is critical.
> 
> Also it was missed as only recently it was pushed in the production

a test should have caught it. The hotfix is applied, but please make a test.

**Comment by burnout87** [comment]
> the redirect should use public url, or better just relative path. Please add a test to make sure that the url_for in this case returns either external url (as in the config) or relative path. I will make a hotfix since it is critical.
> 

Which config entry shall I use?

**Comment by volodymyrss** [comment]
> > the redirect should use public url, or better just relative path. Please add a test to make sure that the url_for in this case returns either external url (as in the config) or relative path. I will make a hotfix since it is critical.
> 
> Which config entry shall I use?

anything different from the address to which it binds

**Comment by burnout87** [comment]
> 
> the redirect should use public url, or better just relative path. Please add a test to make sure that the url_for in this case returns either external url (as in the config) or relative path. I will make a hotfix since it is critical.

#513

**Pull request merged**
