### PR TITLE
Update Flask. Fix plot legend=None issue. Test plugins: add more + better install

### PR DESCRIPTION
**Pull request by dsavchenko**

### CODE REVIEW

**Comment by volodymyrss** [comment]
@dsavchenko antares broke!

**Comment by dsavchenko** [comment]
> @dsavchenko antares broke!

I see, but I can't imagine how this change could affect specifically Antares. 
Will try to figure out what's wrong with it.

**Comment by dsavchenko** [comment]
The error in Antares is coming from the backend. Something seems to be broken again in their data store. 
I will ask Jutta.

**Comment by volodymyrss** [comment]
> The error in Antares is coming from the backend. Something seems to be broken again in their data store. I will ask Jutta.

Do you think it's realistic to wait for this resolved or should we disable antares test? Maybe we could disable and make a PR to reenable at once?

**Comment by dsavchenko** [comment]
@volodymyrss  tests pass now 

PS: I built antares container with older data stored locally for tests

**Comment by volodymyrss** [comment]
> @volodymyrss tests pass now
> 
> PS: I built antares container with older data stored locally for tests

nice, thanks!

**Review by volodymyrss — APPROVED** [review]

**Pull request merged**
