### PR TITLE
some updates on common test request

### PR DESCRIPTION
**Pull request by volodymyrss**
small updates to looping functionlity; should be later moved to another file for better importing

### CODE REVIEW

**Review by burnout87 — APPROVED** [review]
Thanks, actually I had already started to do exactly this. But you have been way faster

**Comment by volodymyrss** [comment]
> Thanks, actually I had already started to do exactly this. But you have been way faster

Yeah sorry I needed to do my LC test which is needed for some eventual test case, would not want it remain broken..

**Comment by volodymyrss** [comment]
thanks!

**Comment by burnout87** [comment]
> > Thanks, actually I had already started to do exactly this. But you have been way faster
> 
> Yeah sorry I needed to do my LC test which is needed for some eventual test case, would not want it remain broken..

no problem! I had in mind exactly the same approach

**Pull request merged**
