### PR TITLE
validation job_id for run_analysis and call_back

### PR DESCRIPTION
**Pull request by burnout87**
Is it helpful to have this check also during a `call_back` ?

### CODE REVIEW

**Review by volodymyrss — CHANGES_REQUESTED** [review]
oh, could we add here more informative message following 

https://github.com/oda-hub/doc-review-guidelines/issues/27

**Comment by volodymyrss** [comment]
> Is it helpful to have this check also during a `call_back` ?

call_back does not provide parameters, no? what would you compare?

**Comment by burnout87** [comment]
> > Is it helpful to have this check also during a `call_back` ?
> 
> call_back does not provide parameters, no? what would you compare?

It would read, within the scratch folder, the analysis_parameters.json and calculate the job_id from it, and then compare the calculated one with the provided one (with, of course, the token considered)

**Comment by volodymyrss** [comment]
> > > Is it helpful to have this check also during a `call_back` ?
> > 
> > 
> > call_back does not provide parameters, no? what would you compare?
> 
> It would read, within the scratch folder, the analysis_parameters.json and calculate the job_id from it, and then compare the calculated one with the provided one (with, of course, the token considered)

this would serve quite different purpose than that with run_analysis. with run_analysis, it is actually possible for client to send incorrect parameters with job_id.
this actually happened.

comparison of `job_id` and `analysis_parameters.json` found in directory with that job_id will only fail if directory is written incorrectly, or call back url was constructed incorrectly.
in principle, this is all internal dispatcher business, but it's good to have for verification.
If not complex, is useful. But then I would rather focus on more impactful issues.

**Comment by burnout87** [comment]
> > > > Is it helpful to have this check also during a `call_back` ?
> > > 
> > > 
> > > call_back does not provide parameters, no? what would you compare?
> > 
> > 
> > It would read, within the scratch folder, the analysis_parameters.json and calculate the job_id from it, and then compare the calculated one with the provided one (with, of course, the token considered)
> 
> this would serve quite different purpose than that with run_analysis. with run_analysis, it is actually possible for client to send incorrect parameters with job_id.
> this actually happened.
> 
> comparison of `job_id` and `analysis_parameters.json` found in directory with that job_id will only fail if directory is written incorrectly, or call back url was constructed incorrectly.
> in principle, this is all internal dispatcher business, but it's good to have for verification.
> If not complex, is useful. But then I would rather focus on more impactful issues.

the check was actually quite easy to implement

**Review by volodymyrss — APPROVED** [review]

**Comment by burnout87** [comment]
After some thoughts I decided to remove the check during `call_back`, since it is out of the scope from the current issue we are addressing, and also to avoid breaking something else

**Comment by volodymyrss** [comment]
> After some thoughts I decided to remove the check during `call_back`, since it is out of the scope from the current issue we are addressing, and also to avoid breaking something else

Ok! We can always leave a TODO in code  and an issue on github, with reference to this PR. This will allow us to come back to it later easily!

**Comment by burnout87** [comment]
#166 for future implementation

**Pull request merged**
