### PR TITLE
Issues on deployment

### PR DESCRIPTION
**Pull request by volodymyrss**

### CODE REVIEW

**Comment by burnout87** [comment]
What is the goal of this ? Is there some issue on deplyment?

**Comment by volodymyrss** [comment]
> What is the goal of this ? Is there some issue on deplyment?

Indeed there are! but consider that this is draft (not ready for review) and review is not requested. I will probably separate it in a couple of different ones.

**Comment by burnout87** [comment]
All right! Let me know so I can also get familiar with the deployment process

**Comment by volodymyrss** [comment]
Well it's really about using it more more practically. Coverage is not too high yet. Need to add more tests for specific cases, appearing with real plugins, etc. Let's see on Monday.

**Comment by volodymyrss** [comment]
I will close this and re-create

**Pull request closed without merging**
