### PR TITLE
additional log

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Review by volodymyrss — APPROVED** [review]

**Comment by burnout87** [comment]
I just need the review before merging

**Comment by volodymyrss** [comment]
> I just need the review before merging

ok, I have a look now!

**Review by volodymyrss — APPROVED** [review]
ok but I did not think too carefully.

could you modify the commit message to express the intent of the config test, it's to check that example config is compatible with both test config versions?

**Comment by burnout87** [comment]
> could you modify the commit message to express the intent of the config test, it's to check that example config is compatible with both test config versions?

Yes, I was rushed a bit and didn't create a very explanatory message. 

I just added an additional test to verify the compatibility of the example config with the both test config versions (with and without the product-gallery related entries).

**Pull request merged**
