### PR TITLE
setting disp_conf in case of resubmission

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by burnout87** [comment]
integral tests fails because of issues in fetching dummy products

**Comment by volodymyrss** [comment]
so you think this helps?

**Comment by burnout87** [comment]
> so you think this helps?

yes I think so

**Comment by volodymyrss** [comment]
Should we do something about the tests?

**Comment by burnout87** [comment]
> Should we do something about the tests?

those that are failing now ? issue is in fetching the dummy products from your personal URL

**Review by dsavchenko — APPROVED** [review]

**Review by volodymyrss — APPROVED** [review]

**Pull request merged**
