### PR TITLE
Bugfix/error when data_server_port (disregarded key) is empty in instrument configuration

### PR DESCRIPTION
**Pull request by dsavchenko**

### CODE REVIEW

**Comment by volodymyrss** [comment]
thanks! this makes sense. But this this is really a bug fix, the incomplete transition leaving unused keys needs to be completed.

**Review by volodymyrss — APPROVED** [review]
thanks, this is ok, but it's a patch to larger incomplete transition

**Comment by dsavchenko** [comment]
> thanks! this makes sense. But this this is really a bug fix, the incomplete transition leaving unused keys needs to be completed.

Ok, I will now deal with other keys. This one was just explicitly disregarded

**Comment by volodymyrss** [comment]
> > thanks! this makes sense. But this this is really a bug fix, the incomplete transition leaving unused keys needs to be completed.
> 
> Ok, I will now deal with other keys. This one was just explicitly disregarded

normally, there are few others also disregarded, I outlined here:

https://github.com/oda-hub/dispatcher-app/issues/24

**Review by volodymyrss — CHANGES_REQUESTED** [review]
actually, I am not sure these additional ones ones can be circumvented.
It's better that the dispatcher crashes on starting without them.

Although, it seems they would need to belong to the plugin?

**Comment by dsavchenko** [comment]
As far as I understand, this class deals with the configuration of an instrument. It should not crash the dispatcher itself.

Anyway, None values are processed in the constructor, so let them go there.

**Comment by volodymyrss** [comment]
if instrument is misconfigured it should crash. 
Error of configuration should not go unnoticed! One way or another. You can also suggest another way to clearly indicate problematic configuration.
Or is it not problematic?

**Comment by volodymyrss** [comment]
since it is a little bit implicit here what is the situation that causes the problem, could you maybe write a test then, so we see what we should define as expected behavior?

**Pull request merged**
