### PR TITLE
removed some fields for products url generation, renamed import, nami…

### PR DESCRIPTION
**Pull request by burnout87**
Adjusted also the naming of some functions. Should now be more consistent with its purpose

### CODE REVIEW

**Comment by burnout87** [comment]
The token, as well as session_id and job_id, are not part the product_url within the email, but it might still be part of the product url from the frontend. Therefore the frontend needs to be updated accordingly

**Comment by volodymyrss** [comment]
> The token, as well as session_id and job_id, are not part the product_url within the email, but it might still be part of the product url from the frontend. Therefore the frontend needs to be updated accordingly

We need to check if frontend actually generates it. It thought it does not, and it really should not. It's better if there is a single function doing it, and it is in the dispatcher already.
Oh, the frontend receives par_dict from dispatcher, this list should be cleaned too.

**Comment by burnout87** [comment]
> > The token, as well as session_id and job_id, are not part the product_url within the email, but it might still be part of the product url from the frontend. Therefore the frontend needs to be updated accordingly
> 
> We need to check if frontend actually generates it. It thought it does not, and it really should not. It's better if there is a single function doing it, and it is in the dispatcher already.
> Oh, the frontend receives par_dict from dispatcher, this list should be cleaned too.

I am not familiar with the frontend code, so perhaps I looked in the wrong place, but it seems like that such url is generated.

The list of ignored fields should be updated, to make things easy of course.

[https://github.com/oda-hub/frontend-astrooda/blob/86b9874b1a2d927f9dbf25c940e46ee7f26adfe1/js/astrooda.instrument.js#L1277-L1294](https://github.com/oda-hub/frontend-astrooda/blob/86b9874b1a2d927f9dbf25c940e46ee7f26adfe1/js/astrooda.instrument.js#L1277-L1294)

**Review by volodymyrss — CHANGES_REQUESTED** [review]
hm, ok, but a test?

**Comment by burnout87** [comment]
> hm, ok, but a test?

The current test in `test_job_management` currently checks the product url, just not directly but using the content of thje email

**Comment by volodymyrss** [comment]
> > > The token, as well as session_id and job_id, are not part the product_url within the email, but it might still be part of the product url from the frontend. Therefore the frontend needs to be updated accordingly
> > 
> > 
> > We need to check if frontend actually generates it. It thought it does not, and it really should not. It's better if there is a single function doing it, and it is in the dispatcher already.
> > Oh, the frontend receives par_dict from dispatcher, this list should be cleaned too.
> 
> I am not familiar with the frontend code, so perhaps I looked in the wrong place, but it seems like that such url is generated.
> 
> The list of ignored fields (`ignore_params_url`) should be updated, to make things easy of course.
> 
> https://github.com/oda-hub/frontend-astrooda/blob/86b9874b1a2d927f9dbf25c940e46ee7f26adfe1/js/astrooda.instrument.js#L1277-L1294

indeed! Good point.
I started to doubt it fully comes from the dispatcher when I did not see it in the response.
It gives you an idea what is ignored.
What is unfortunate is that ignore_params_url should be now synchronized with its done by generate_products_url_from_par_dict.
Maybe in the future we can make sure they come from the same place.
But for now, can we make it as you suggest and make a TODO comment?
Feel free to make a PR on frontend-astrooda!
We have now couple of PRs on there, we should agree with @motame tomorrow how to handle them efficiently.

**Comment by burnout87** [comment]
> > `test_job_management`
> 
> but it does not test that newly ignored keys are ignored.

I check now that the product url I expect does not contain the ignored parameters, before checking the entire content of the received email.

**Review by volodymyrss — APPROVED** [review]

**Pull request merged**
