### PR TITLE
Optional job id and session

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Review by volodymyrss — CHANGES_REQUESTED** [review]
could you also add "produced_by" argument to mitigate reduction of reproducibility?

and also we'll need an example in oda_api. An issue there?

**Comment by burnout87** [comment]
> 
> and also we'll need an example in oda_api. An issue there?

actually oda_apii will need some extension, I will provided that once the field `produced_by` is implemented

**Comment by burnout87** [comment]
ok the produced by field is now thgere, I am working now on the best formatting for that link

**Comment by burnout87** [comment]
> ok the produced by field is now thgere, I am working now on the best formatting for that link

Output example

image


[http://cdciweb02.isdc.unige.ch/mmoda/gallery/node/1298](http://cdciweb02.isdc.unige.ch/mmoda/gallery/node/1298)

**Pull request merged**
