### PR TITLE
Include commit renku url

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by burnout87** [comment]
URL example:

http://renkulab.io/projects/gabriele.barni/test-dispatcher-endpoint/sessions/new?autostart=1&branch=mmoda_request_701a79e362587f0e&commit=c035cb9fc37ca7f6b9bc0d37c23f130184b1cb99

**Comment by volodymyrss** [comment]
thanks!

to be clear, from what I understood from the last meeting and from the discussion here https://github.com/SwissDataScienceCenter/renku-ui/issues/1800

this change will help, but will not resolve the entire issue.

I just wanted to say this the record.

**Comment by burnout87** [comment]
> thanks!
> 
> to be clear, from what I understood from the last meeting and from the discussion here [SwissDataScienceCenter/renku-ui#1800](https://github.com/SwissDataScienceCenter/renku-ui/issues/1800)
> 
> this change will help, but will not resolve the entire issue.
> 
> I just wanted to say this the record.

No, the issue is on their side. In the meantime let's see if it helps

**Comment by burnout87** [comment]
> oh you could probably take first 8 characters of the commit hash, to keep the URL shorter.

Did they mention it? I don't recall it, but ok

**Comment by volodymyrss** [comment]
> > thanks!
> > to be clear, from what I understood from the last meeting and from the discussion here [SwissDataScienceCenter/renku-ui#1800](https://github.com/SwissDataScienceCenter/renku-ui/issues/1800)
> > this change will help, but will not resolve the entire issue.
> > I just wanted to say this the record.
> 
> No, the issue is on their side. In the meantime let's see if it helps

we know this will address the issue partially, and we know how. Should not be much more to see! Unless there is any further misunderstanding.

**Comment by burnout87** [comment]
> 
> this is a general git thing, they do not need to mention it. Please try if it works.

https://renkulab.io/projects/gabriele.barni/test-dispatcher-endpoint/sessions/new?autostart=1&branch=mmoda_request_701a79e362587f0e&commit=1a712f93

does not seem to work

image

**Comment by volodymyrss** [comment]
ok well that's unfortunate.

**Review by volodymyrss — DISMISSED** [review]

**Pull request merged**
