### PR TITLE
url expiration time in email template

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by volodymyrss** [comment]
That's just it, thanks! 
I am only wondering, there is not test that breaks because of this change?..

**Comment by burnout87** [comment]
> That's just it, thanks! I am only wondering, there is not test that breaks because of this change?..

I was just checking it, apparently not, we have only tests with permanent url

**Comment by burnout87** [comment]
> That's just it, thanks! I am only wondering, there is not test that breaks because of this change?..

I will extend one test, so it'll check this too

**Comment by burnout87** [comment]
> > That's just it, thanks! I am only wondering, there is not test that breaks because of this change?..
> 
> I will extend one test, so it'll check this too

Now it's there

**Review by volodymyrss — APPROVED** [review]
thanks!

**Pull request merged**
